### ISSUE TITLE
Adicionar uso de contexto ao projeto 

### ISSUE THREAD

**Issue by mateusoliveira2** [mateusmangueira/dev-web-project#10]
Seria interessante usar em partes do sistema que os dados devem ser compartilhados ou são considerados globais, como autenticação de usuário.

**Comment by mateusmangueira** [comment]
Utilizei o useContext no projeto para compartilhar dados globais no projeto, segue o commit: https://github.com/mateusmangueira/dev-web-project/commit/80d172e0873f864d7a8ef678d4992637e36d816a
