### ISSUE TITLE
estrutura de pastas -hooks

### ISSUE THREAD

**Issue by lucasaires** [mateusmangueira/dev-web-project#12]
Não é algo que vá impactar na aplicação, mas usualmente utiliza-se o "hooks" para denominar a pasta com os contextos, seria bom deixa-la no pasta src, isolado do Utils.

**Comment by mateusmangueira** [comment]
Beleza, Lucas. Já fiz a modificação sugerida, obrigado pelo feedback! Segue o commit: https://github.com/mateusmangueira/dev-web-project/commit/8879f7ef607a9414f70eafb88533ac494f0cc5f7
