### ISSUE TITLE
Adicionar mais informações ao Readme

### ISSUE THREAD

**Issue by RaylaMedeiros** [mateusmangueira/dev-web-project#3]
Acho que você poderia explicar mais sobre a problemática do seu projeto no Readme, dar mais informações sobre o projeto, ao invés de ter focado em só em descrever as telas que vão existir. Porque por exemplo, as telas podem mudar ao longo do seu desenvolvimento, mas ai já fica mais claro o seu objetivo com o projeto.

**Comment by mateusmangueira** [comment]
Fiz o ajuste solicitado, muito obg pelo feedback!
