### ISSUE TITLE
CustomButton não recebe as props que estão sendo passadas

### ISSUE THREAD

**Issue by thayannevls** [mateusmangueira/dev-web-project#4]
Olá 👋 

Acredito que foi um detalhe que passou batido, mas o componente `CustomButton` não recebe todas as props que estão sendo passadas(como `onClick`). Está recebendo apenas o `text`. Uma alternativa boa para cobrir todas as props que um componente precisa é usar spread na hora de pegar as props:

```js
export default function CustomButton({text, ...props}) {
  return (
    <Button {...props}>
      {text}
    </Button>
  );
}
```

Por conta disso, o modal não está abrindo nas telas

**Comment by mateusmangueira** [comment]
Oii, Thayanne!

Fiz os ajustes, muito obrigado pelo feedback!
