### ISSUE TITLE
Estrutura confusa na página de registro

### ISSUE THREAD

**Issue by thayannevls** [mateusmangueira/dev-web-project#5]
Acredito que haja um erro na estrutura da página nessa [parte](https://github.com/mateusmangueira/dev-web-project/blob/main/frontend/src/pages/Register/index.js#L20~L25). Não faz muito sentido o modal está como children do botão, acredito que se estivesse funcionando o onClick do botão, faria o modal renderizar estranho na página.

O ideal seria talvez isolar o modal de registro em um novo componente já que imagino que ele vá ter mais lógica no futuro, e daí seria algo assim:

```jsx
return (
    <div>
      <Link to="/">Login</Link>
      <hr></hr>
      <CustomButton onClick={handleModal} text="Registrar"/>
        <RegisterModal show={showModal} handleClose={handleModal} />
    </div>
  )
```

**Comment by mateusmangueira** [comment]
Faz sentindo, retirei o Modal por enquanto do projeto... Caso, futuramente, eu precise eu retorno e sigo a estrutura que você me passou como feedback. 

Obrigado!
