### ISSUE TITLE
Sugestão de configuração

### ISSUE THREAD

**Issue by RaylaMedeiros** [mateusmangueira/dev-web-project#6]
Muito boa a estruturação do projeto. Apenas uma sugestão, a criação de um arquivo `.env` para adicionar algumas variáveis de ambiente, ao invés de colocar diretamente no código, como por exemplo a url da api.

**Comment by adrianora** [comment]
Além que é uma alteração bem simples de fazer, basta usar o `process.env.<nome_da_variavel>` que é fornecido nativamente pela ferramenta, então ela mesmo vai buscar a variável que foi definida no arquivo .env, localizado na raiz do projeto.

**Comment by mateusmangueira** [comment]
Obrigado pelo feedback Rayla e Adriano, já configurei o dotenv no projeto
